.PHONY: clean All

All:
	@echo "----------Building project:[ CarPi - Debug ]----------"
	@$(MAKE) -f  "CarPi.mk"
clean:
	@echo "----------Cleaning project:[ CarPi - Debug ]----------"
	@$(MAKE) -f  "CarPi.mk" clean
